# Generated by Django 6.0.7 on 2026-08-19 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('modelo', models.CharField(default='ESP32 - Sensor de Gás', max_length=50)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Manutenção', 'Manutenção')], default='Ativo', max_length=20)),
                ('ultima_comunicacao', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(choices=[('Casa', 'Casa'), ('Apartamento', 'Apartamento'), ('Empresa', 'Empresa'), ('Comércio', 'Comércio')], max_length=20)),
                ('descricao', models.CharField(max_length=150)),
                ('endereco', models.CharField(max_length=200)),
                ('dispositivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='localizacao', to='sensores.dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('temperatura', models.DecimalField(decimal_places=1, max_digits=4)),
                ('umidade', models.DecimalField(decimal_places=1, max_digits=4)),
                ('gas_ppm', models.IntegerField()),
                ('nivel_gas', models.CharField(choices=[('Normal', 'Normal'), ('Atenção', 'Atenção'), ('Perigo', 'Perigo'), ('Inativo', 'Inativo')], max_length=10)),
                ('vazamento', models.BooleanField()),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='sensores.dispositivo')),
            ],
        ),
    ]
