# Generated by Django 6.0.7 on 2026-08-21 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='gas_ppm',
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='bateria',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='rede_conectada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registro',
            name='gas_percentual',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='temperatura',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='registro',
            name='umidade',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
