# Generated by Django 6.0.7 on 2026-09-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0002_remove_registro_gas_ppm_dispositivo_bateria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='temperatura',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='registro',
            name='umidade',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
